//API OPen weather map
//Capturar elementos de DOMos
let container = document.getElementById('container');
let searchForm = document.getElementById('search__submit');
let searchInput = document.getElementById('search__input');
let temperatureDegrees = document.getElementById('degreeNumber');
let weatherIcon = document.getElementById('weatherIcon');
let temperatureDescription = document.getElementById('description');
let timeZone = document.getElementById('timezone');
let date = document.getElementById('date');
let min = document.getElementById('min');
let max = document.getElementById('max');